### ISSUE TITLE
Set the amplitude and scaling factor of the whisker stimulus vector in the GUI.

### ISSUE THREAD

**Issue by aprrenard** [LSENS-BMI-EPFL/behavior_control#17] opened 2023-02-15 14:39 UTC
Currently we use the calibration file to check that the whisker stimulus is delivered at 40 mT. After finding an appropriate voltage, this value must be adjusted in the code. We want to do this adjustment from the GUI byt setting those parameters at the start of the session, not by changing a hard coded stimulus. The scaling factor does not need to change for small adjustments, but should be editable if needed. And those two parameters should go in the json file.

**Comment by abisi** [comment] 2023-02-15 14:47
Yep! Not sure when this should be done. For now I'll set this manually to keep confidence in my calibration. Also, duplicate of #11, so deleting issue #11

**Closed** 2023-03-25 14:42 UTC
